In [85]:
import numpy as np
import pandas as pd

arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr2 = np.zeros((3, 3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
arr3 = np.eye(4)
arr3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [88]:
arr4 = np.identity(4)
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [89]:
print(f"Min : {arr1.min()}")
print(f"Max : {arr1.max()}")
print(f"Mean : {arr1.mean()}")
print(f"Sum : {arr1.sum()}")

Min : 0
Max : 10
Mean : 5.0
Sum : 55


In [90]:
print(f"Min : {np.min(arr1)}")
print(f"Max : {np.max(arr1)}")
print(f"Mean : {np.mean(arr1)}")
print(f"Sum : {np.sum(arr1)}")

Min : 0
Max : 10
Mean : 5.0
Sum : 55


In [91]:
arr1 = arr1 * 2
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [92]:
arr1[arr1 > 25]

array([], dtype=int64)

In [93]:
arr1[arr1 > 10]

array([12, 14, 16, 18, 20])